version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 303120020603.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t public.ecr.aws/w0l2m1u4/nn-rocket_test:latest .
      - docker tag public.ecr.aws/w0l2m1u4/nn-rocket_test:latest 303120020603.dkr.ecr.us-east-1.amazonaws.com/public.ecr.aws/w0l2m1u4/nn-rocket_test:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 303120020603.dkr.ecr.us-east-1.amazonaws.com/public.ecr.aws/w0l2m1u4/nn-rocket_test:latest

